"""
lightingconsts.py

This file contains constants regarding lights

Author: Miguel Guthridge
"""

# Define colour codes
COLOUR_TRANSPARENT = -1
COLOUR_OFF = 0
COLOUR_WHITE = 3
COLOUR_RED = 5
COLOUR_GREEN = 25
COLOUR_PINK = 53
COLOUR_BLUE = 46
COLOUR_YELLOW = 13
COLOUR_PURPLE = 49
COLOUR_LILAC = 116
COLOUR_ORANGE = 84

COLOUR_LIGHT_YELLOW = 109
COLOUR_LIGHT_BLUE = 37
COLOUR_LIGHT_LILAC = 116
COLOUR_LIGHT_LIGHT_BLUE = 40

COLOUR_DARK_GREY = 1
COLOUR_DARK_PURPLE = 51
COLOUR_DARK_BLUE = 47
COLOUR_DARK_RED = 59

# Define colour pallettes used by light show
PALLETE_NORMAL = [COLOUR_RED, COLOUR_PINK, COLOUR_PURPLE, COLOUR_BLUE, COLOUR_LIGHT_BLUE, COLOUR_GREEN, COLOUR_YELLOW, COLOUR_ORANGE, COLOUR_OFF]
PALLETE_INIT_FAIL = [COLOUR_YELLOW, COLOUR_ORANGE, COLOUR_ORANGE, COLOUR_RED, COLOUR_RED, COLOUR_ORANGE, COLOUR_ORANGE, COLOUR_YELLOW, COLOUR_OFF] 
PALLETE_UPDATE = [COLOUR_BLUE, COLOUR_LIGHT_BLUE, COLOUR_LIGHT_BLUE, COLOUR_GREEN, COLOUR_GREEN, COLOUR_LIGHT_BLUE, COLOUR_LIGHT_BLUE, COLOUR_BLUE, COLOUR_OFF] 

# Define UI colours
UI_NAV_VERTICAL = COLOUR_LIGHT_BLUE
UI_NAV_HORIZONTAL = COLOUR_PURPLE
UI_ZOOM = COLOUR_BLUE
UI_ACCEPT = COLOUR_GREEN
UI_REJECT = COLOUR_RED
UI_CHOOSE = COLOUR_PURPLE

UI_UNDO = COLOUR_LIGHT_LIGHT_BLUE
UI_REDO = COLOUR_LIGHT_BLUE

UI_COPY = COLOUR_BLUE
UI_CUT = COLOUR_LIGHT_BLUE
UI_PASTE = COLOUR_GREEN

UI_SAVE = COLOUR_GREEN

# Define tool colours
TOOL_PENCIL = COLOUR_ORANGE
TOOL_BRUSH = COLOUR_LIGHT_BLUE
TOOL_DELETE = COLOUR_RED
TOOL_MUTE = COLOUR_PINK
TOOL_SLIP = COLOUR_ORANGE
TOOL_SLICE = COLOUR_LIGHT_BLUE
TOOL_SELECT = COLOUR_YELLOW
TOOL_ZOOM = COLOUR_BLUE
TOOL_PLAYBACK = COLOUR_GREEN

# Define Window Colours
WINDOW_PLAYLIST = COLOUR_GREEN
WINDOW_CHANNEL_RACK = COLOUR_RED
WINDOW_PIANO_ROLL = COLOUR_PINK
WINDOW_MIXER = COLOUR_LIGHT_BLUE
WINDOW_BROWSER = COLOUR_ORANGE
WINDOW_PLUGIN_PICKER = COLOUR_BLUE

# Define Beat Indicator Colours
BEAT_PAT_BAR = COLOUR_RED
BEAT_PAT_BEAT = COLOUR_ORANGE
BEAT_SONG_BAR = COLOUR_LIGHT_BLUE
BEAT_SONG_BEAT = COLOUR_GREEN

TEMPO_TAP = COLOUR_PINK
METRONOME = COLOUR_DARK_GREY

# Colour Matrix for errors
ERROR_COLOURS = [
    [COLOUR_RED, COLOUR_RED],
    [COLOUR_RED, COLOUR_RED],
    [COLOUR_RED, COLOUR_RED],
    [COLOUR_RED, COLOUR_RED],
    [COLOUR_RED, COLOUR_RED],
    [COLOUR_RED, COLOUR_RED],
    [COLOUR_RED, COLOUR_RED],
    [COLOUR_RED, COLOUR_RED],
    [COLOUR_RED, COLOUR_RED]
]
